import type { DecorItem } from "@/lib/types";

export const DECOR: DecorItem[] = [
  {
    id: "woven-bed",
    name: "Woven Bed",
    roomId: "living",
    costDecorTokens: 0,
    slot: "floor",
  },
  {
    id: "star-lamp",
    name: "Star Lamp",
    roomId: "sleeping",
    costDecorTokens: 1,
    slot: "accent",
  },
  {
    id: "sunny-rug",
    name: "Sunny Rug",
    roomId: "living",
    costDecorTokens: 2,
    slot: "floor",
  },
  {
    id: "herb-window",
    name: "Herb Window",
    roomId: "kitchen",
    costDecorTokens: 2,
    slot: "wall",
  },
  {
    id: "rope-toy-basket",
    name: "Rope Toy Basket",
    roomId: "living",
    costDecorTokens: 3,
    slot: "floor",
  },
  {
    id: "bubble-mat",
    name: "Bubble Mat",
    roomId: "bath",
    costDecorTokens: 2,
    slot: "floor",
  },
  {
    id: "garden-bowl",
    name: "Garden Water Bowl",
    roomId: "backyard",
    costDecorTokens: 2,
    slot: "floor",
  },
  {
    id: "layered-blanket-nest",
    name: "Layered Blanket Nest",
    roomId: "sleeping",
    costDecorTokens: 0,
    slot: "floor",
    requiresPremiumId: "cozy-blanket-set",
  },
  {
    id: "zoomie-toy-pyramid",
    name: "Zoomie Toy Pyramid",
    roomId: "living",
    costDecorTokens: 0,
    slot: "floor",
    requiresPremiumId: "zoomie-toy-pack",
  },
  {
    id: "frosted-seasonal-pane",
    name: "Frosted Seasonal Pane",
    roomId: "seasonal",
    costDecorTokens: 0,
    slot: "wall",
    requiresPremiumId: "seasonal-backdrop",
  },
  {
    id: "starlit-memory-runner",
    name: "Starlit Memory Runner",
    roomId: "memory",
    costDecorTokens: 0,
    slot: "floor",
    requiresPremiumId: "starlit-rug",
  },
];
